export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FETCH_ALL_POST = "FETCH_ALL_POST";
export const FETCH_ALL_POST_FAILED = "FETCH_ALL_POST_FAILED";
export const STORE_ALL_POST = "STORE_ALL_POST";
